name: symbol_table
version: 2.0.0
description: A generic symbol table implementation in Dart, with support for scopes and constants.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/symbol_table
environment:
  sdk: ">=2.19.1 <3.0.0"
#  sdk: ">=2.0.0-dev <3.0.0"
dev_dependencies:
  test: ^1.0.0