name: dartjsengine
description: JS engine for Dart.
author: Anurag Vohra<anuragvohraec@gmail.com>
homepage: https://github.com/anuragvohraec/dartJSEngine.git
version: 1.0.1

environment:
  sdk: ">=2.19.1 <3.0.0"
#  sdk: ">=2.4.0 <3.0.0"

dependencies:
  jsparser:
    path: ../jsparser-2.0.1
  symbol_table:
    path: ../symbol_table-2.0.0
dev_dependencies:
  test: ^1.6.5


